#!/bin/bash
clear

# instantWebDev is released under the apache v2.0 License http://www.apache.org/licenses/LICENSE-2.0
# Created By: Grant Hutchinson(hutchgrant)
# github.com/hutchgrant/instantWebDev

# -------------------------------------------#
#         REMOTE DRUPAL SITES INFO
# -------------------------------------------#
# ADD/EDIT WITH YOUR REMOTE SITES
declare -A arr
arr[1,'site']="example.com"		    # Remote Site Name
arr[1,'ssh']="root@8.8.8.8"	            # SSH user@ipaddress
arr[1,'locMnt']="/home/user/sites/example"  # Local Folder for mounting your site
arr[1,'remMnt']="/var/www/example"          # Remote apache folder where the site is located
arr[1,'multisite']="example-multi.com"      # multisite directory name for drush to update, if no default site

arr[2,'site']="example2.com"
arr[2,'ssh']="root@8.8.8.8"
arr[2,'locMnt']="/home/user/sites/example2"
arr[2,'remMnt']="/var/www/example2"

arr[3,'site']="example3.com"
arr[3,'ssh']="root@8.8.8.8"
arr[3,'locMnt']="/home/user/sites/example3"
arr[3,'remMnt']="/var/www/example3"

count=3  # EDIT adjust for number of remote sites you add. Multidimensional, difficulty ascertaining size automatically
# -------------------------------------------#
#  LOCAL DRUPAL/WORDPRESS CREATE SITE INFO
# -------------------------------------------#
# EDIT WITH YOUR MYSQL CREDENTIALS
db_user="root"
db_pass="password"
db_url="localhost"

# EDIT WITH YOUR PREFERRED DRUPAL/WORDPRESS DEFAULT ADMIN CREDENTIALS
Usr="admin"
Pass="password"
Email="example@example.com"

# FOR CUSTOM PATHS, EDIT THESE
srvRoot="/home/$USER/public_html"
srvUrl="http://localhost/~$USER"
base="/~$USER"

localDrushAlias="local"

# ------------------------------------------#
# -------- Custom Default Themes -----------#
# ------------------------------------------#
author="$USER"

# Drupal Themes
declare -A druptheme
druptheme[1,'name']="Bootstrap 3"		    		   # Drupal Theme Name -exact dl name
druptheme[1,'desc']="Bootstrap 3 Base Theme"	    		   # Drupal Theme Description

drupthemeCount=1  # EDIT adjust for number of drupal themes you add.

# Wordpress Themes
declare -A wordtheme
wordtheme[1,'name']="bst				"	             # Wordpress Theme Name -exact dl name
wordtheme[1,'desc']="Bootstrap 3 Starter Theme by SimonPadbury"	             # Wordpress Theme Description
wordtheme[1,'url']="https://github.com/SimonPadbury/bst/archive/master.zip"  # URL to download from

wordtheme[2,'name']="b4st"					             # Wordpress Theme Name -exact dl name
wordtheme[2,'desc']="Bootstrap 4-alpha Starter Theme by SimonPadbury"	     # Wordpress Theme Description
wordtheme[2,'url']="https://github.com/SimonPadbury/b4st/archive/master.zip" # URL to download from

wordthemeCount=2 # EDIT adjust for number of wordpress themes you add.



# Check if apache mod_rewrite is enabled
checkRewrite () {

if [ ! -f /etc/apache2/mods-enabled/rewrite.load ]; then
    echo "Apache mod_rewrite not enabled, enabling..."
    sudo a2enmod rewrite
    sudo service apache2 restart;
fi

}

# Check if apache mod_userdir is enabled
checkUserDir () {

if [ ! -f /etc/apache2/mods-enabled/userdir.load ]; then
    echo "Apache mod_userdir not enabled, enabling..."
    sudo a2enmod userdir
    echo "creating ~/public_html directory for your sites"
    mkdir ~/public_html && chmod 0755 ~/public_html
    echo "editing /etc/apache2/mods-available/php7.0.conf to enable php in your public_html directory"
    sudo sed -e '/php_admin_flag/ s/^#*/#/' -i /etc/apache2/mods-available/php7.0.conf
    sudo service apache2 restart;
fi

}

# Check for LAMP
checkLAMP () {

if ! [ -x "$(command -v apache2)" ]; then
if [ "`lsb_release -is`" == "Ubuntu" ] || [ "`lsb_release -is`" == "Debian" ]
then
    echo -e "\n Missing LAMP server! Attempting to install Apache2, MySQL, PHP7, phpmyadmin"
    echo "-------------------------------------------------------------------------------"
    echo "----REMINDER: You will be asked to create and then re-enter a mysql password----"
    echo "------------- Make sure you write it down, you will need to manually edit -----"
    echo "--------------the top of this script with it after it's completed or it -------"
    echo "--------------will not work!---------------------------------------------------"
    echo "-------------------------------------------------------------------------------"
    read -p "Press any key to continue..." 
    sudo apt-get -y install mysql-server mysql-client libmysqld-dev;
    sudo apt-get -y install apache2 php7.0 libapache2-mod-php php-mcrypt phpmyadmin;
    sudo chmod 755 -R /var/www/;
    sudo printf "<?php\nphpinfo();\n?>" > /var/www/html/info.php;
    checkRewrite
    checkUserDir
    echo "-------------------------------------------------------------------------------"
    echo "-------------------------------------------------------------------------------"
    echo "LAMP install completed. You can now put your sites in /var/www/ accessible by with http://127.0.0.1/yoursite"
    echo "This script will put your sites in /home/$USER/public_html and you can access it with http://localhost/~$USER/yoursite"
    echo "-------------------------------------------------------------------------------"
    echo "To continue installing your first site, we need the mysql password, it's recommended you manually edit it into the top of this script, along with other credentials you want to add, then save it. rerun this script afterwords when completed".
    echo "---------------------------------------------------------------------------------"
    read -p "Press any key to continue..."
    gedit ./instantWebDev
    exit
else
    echo "Missing LAMP server for your distribution, you'll have to install it and run again."
    exit
fi
else
    checkRewrite
    checkUserDir
fi

}

# Check for drush
checkDrush () {

if ! [ -x "$(command -v drush)" ]; then
	echo "Drush is missing, atempting to install drush"
	if ! [ -x "$(command -v php)" ]; then
		echo "you must install php first to continue. sudo apt-get install php"
		exit
	fi
	sudo apt-get install drush -y
	cd ~/
	php -r "readfile('http://files.drush.org/drush.phar');" > drush
	drushlocation="$(which drush)"
	chmod +x ~/drush
	sudo mv ~/drush $drushlocation
	$drushlocation init
fi

}

# Check for WP-CLI 
checkWPCLI () {

if ! [ -x "$(command -v wp)" ]; then
	echo "WP-CLI is missing, atempting to install"
	if ! [ -x "$(command -v curl)" ]; then
		echo "you must install curl first to continue. sudo apt-get install curl"
		exit
	fi
	cd ~/
	curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
	chmod +x ~/wp-cli.phar
	sudo mv ~/wp-cli.phar /usr/local/bin/wp
fi

}

# Create Single Drupal site
singleDrupal () {

## create alias / alias group
if [ ! -f ~/.drush/local.aliases.drushrc.php ]; then
    echo "drush local alias not found! Creating a new alias group ~/.drush/local.aliases.drushrc.php"
    sudo echo -e "<?php \n" > /home/$USER/.drush/local.aliases.drushrc.php
fi

sudo sh -c "echo \"\\\$aliases['$newsite'] = array( \n \
    'uri' => '$srvUrl/$newsite/', \n \
    'root' => '$srvRoot/$newsite', \n \
); \n\" >> /home/$USER/.drush/local.aliases.drushrc.php"

## Download and extract drupal
drush dl drupal --destination="$srvRoot" --drupal-project-rename="$newsite"

cd $srvRoot/$newsite

## Install and configure drupal
drush -y @local.$newsite site-install standard --db-url=mysql://$db_user:$db_pass@$db_url/$newsite --account-mail="$Email" --account-name="$Usr" --account-pass="$Pass" --site-name="$newsite"

## Set drupal permissions
chmod 777 $srvRoot/$newsite/sites/default/files

## clear cache
drush @local.$newsite cache-rebuild

}


# Add multisite subdirectory to Drupal site
multiDrupal () {

## Install and configure drupal
drush -y @local.$baseSite site-install standard --db-url=mysql://$db_user:$db_pass@$db_url/$newsite --sites-subdir="$newsite" --account-mail="$Email" --account-name="$Usr" --account-pass="$Pass" --site-name="$newsite"

## Add new multisite config to sites.php
sed -i "/);/i \'localhost.~$USER.$newsite' => '$newsite', " $srvRoot/$baseSite/sites/sites.php

## Link folder in base directory to site
ln -s $srvRoot/$baseSite $srvRoot/$newsite
## Set drupal permissions
chmod 777 $srvRoot/$baseSite/sites/$newsite/files

## clear cache of multisite
drush @local.$baseSite -l $newsite cache-rebuild

}

# Download, Extract, Configure Wordpress
setupWP () {

## download WP
wp core download --path=$srvRoot/$newsite

## configure
wp core config --dbhost=$db_url --dbname=$newsite --dbuser=$db_user --dbpass=$db_pass --path=$srvRoot/$newsite

## create DB
wp db create --path=$srvRoot/$newsite
}

# Create Single Wordpress Site
singleWP () {

setupWP

## install WP
wp core install --url=$srvUrl/$newsite --title=$newsite --admin_user=$Usr --admin_password=$Pass --admin_email=$Email --path=$srvRoot/$newsite

}

# Create Multi Wordpress Site
multiWP () {

setupWP

## install WP multisite
wp core multisite-install --url=$srvUrl/$newsite --title=$newsite --admin_user=$Usr --admin_password=$Pass --admin_email=$Email --path=$srvRoot/$newsite --base=$base/$newsite/

## add .htaccess rewrite rules
echo -e "RewriteEngine On  \n \
RewriteBase $base/$newsite/  \n \
RewriteRule ^index\.php$ - [L] \n \

# add a trailing slash to /wp-admin  \n \
RewriteRule ^([_0-9a-zA-Z-]+/)?wp-admin$ \$1wp-admin/ [R=301,L]  \n \

RewriteCond %{REQUEST_FILENAME} -f [OR]  \n \
RewriteCond %{REQUEST_FILENAME} -d \n \
RewriteRule ^ - [L] \n \
RewriteRule ^([_0-9a-zA-Z-]+/)?(wp-(content|admin|includes).*) \$2 [L] \n \
RewriteRule ^([_0-9a-zA-Z-]+/)?(.*\.php)$ \$2 [L] \n \
RewriteRule . index.php [L]" > $srvRoot/$newsite/.htaccess

}

# modify Apache config and restart
modifyApache () {

sudo sed -i '/# Available/i\ <Directory "'$srvRoot/$newsite'" > \
            Options Indexes FollowSymLinks MultiViews \
            AllowOverride All \
            Order allow,deny \
            allow from all \
        </Directory> \n ' /etc/apache2/sites-available/000-default.conf

sudo service apache2 restart

}

# open browser to display site
openSite () {

if ! [ -x "$(command -v google-chrome)" ]; then
    firefox $srvUrl/$newsite
else
    google-chrome $srvUrl/$newsite
fi

## Open sublime/nautilus
if ! [ -x "$(command -v subl)" ]; then
    echo "sublime not installed, opening nautilus"
    nautilus $srvRoot/$newsite
else
    subl $srvRoot/$newsite
fi

}

# Get multisite base site name
getMultiName () {
	echo "Which multisite(pre-existing drupal site dir name) do you want to add to?"
	read baseSite
}

# Update all Remote Drupal Installations
updateRemDrupal () {
for (( i=1; i<=$count; i++))
do
  ssh ${arr[$i,'ssh']} << EOF
   apt-get -y upgrade
   cd ${arr[$i,'remMnt']}
   if [ -n "${arr[$i,'multisite']}" ]; then
   drush -l ${arr[$i,'multisite']} pm-update -y
   else
   drush pm-update -y
   fi
   exit
EOF
done
}

# Check for less
checkLess () {

if ! [ -x "$(command -v lessc)" ]; then
	echo "Less is missing, atempting to install Less"
	sudo apt-get install less -y
fi

}

# Install New Bootstrap Base Theme
installDrupTheme () {

checkLess
# Get bootstrap default theme + start kit, create new theme
drush @local.$newsite en bootstrap -y
cp $srvRoot/$newsite/themes/bootstrap/starterkits/less $srvRoot/$newsite/themes/$themename -R
find $srvRoot/$newsite/themes/$themename/ -name "THEMENAME*" -exec rename "s/THEMENAME/$themename/" '{}' \;
mv $srvRoot/$newsite/themes/$themename/$themename.starterkit.yml $srvRoot/$newsite/themes/$themename/$themename.info.yml 
find $srvRoot/$newsite/themes/$themename/ -exec sed -i "s/THEMENAME/$themename/g" '{}' \;

# Get bootstrap source
wget https://github.com/twbs/bootstrap/archive/v3.3.7.zip -P $srvRoot/$newsite/themes/
unzip $srvRoot/$newsite/themes/v3.3.7.zip -d $srvRoot/$newsite/themes/$themename/
mv $srvRoot/$newsite/themes/$themename/bootstrap-3.3.7 $srvRoot/$newsite/themes/$themename/bootstrap
rm $srvRoot/$newsite/themes/v3.3.7.zip

lessc $srvRoot/$newsite/themes/$themename/less/style.less $srvRoot/$newsite/themes/$themename/css/style.css

echo "enable on a specific multisite? [y/n]"
read multisite


if [ $multisite == "y" ]; then
echo "Which sub-site of this multisite do you want to enable the theme on?"
read specmulti

drush @local.$newsite -l $specmulti pm-uninstall bartik
drush @local.$newsite -l $specmulti pm-enable $themename -y
drush @local.$newsite -l $specmulti config-set system.theme default $themename -y
drush @local.$newsite -l cache-rebuild
else
drush @local.$newsite pm-uninstall bartik
drush @local.$newsite pm-enable $themename -y
drush @local.$newsite config-set system.theme default $themename -y
drush @local.$newsite cache-rebuild
fi

}

# Install New Wordpress base Theme
installWordTheme () {
wp theme install ${wordtheme[$themechoice,'url']} --path=$srvRoot/$newsite

cp $srvRoot/$newsite/wp-content/themes/${wordtheme[$themechoice,'name']} $srvRoot/$newsite/wp-content/themes/$themename -R
rm $srvRoot/$newsite/wp-content/themes/${wordtheme[$themechoice,'name']} -R

echo -e "/*
Theme Name: $themename 
Theme URI: http://$author.com 
Description: Bootstrap Starter Theme for WordPress. Using Twitter Bootstrap 3.3.5
Author: $author
Author URI: http://$author.github.io
Version: 2.7.1
License: MIT License
License URI: http://opensource.org/licenses/MIT 
*/ \n" > $srvRoot/$newsite/wp-content/themes/$themename/style.css

echo "Activate theme immediately on this site? [y/n]"
read themeactive

echo "Enable theme for all sites on a multisite? [y/n]"
read thememulti

if [ $themeactive == "y" ]; then
if [ $thememulti == "y" ]; then
wp theme enable $themename --path=$srvRoot/$newsite --activate --network
else
wp theme activate $themename --path=$srvRoot/$newsite
fi
fi
}

# List Drupal Themes
drupThemeList () {
for (( i=1; i<=$drupthemeCount; i++))
do
  echo "$i) ${druptheme[$i,'desc']}"
done
read themechoice
}

# List Wordpress Themes
wordThemeList () {
for (( i=1; i<=$wordthemeCount; i++))
do
  echo "$i) ${wordtheme[$i,'desc']}"
done
read themechoice
}

# Display New Drupal Theme Menu
drupThemeMenu () {
echo "Do you want to create a new theme? [y/n]"
read newtheme

if [ $newtheme == "y" ]; then
echo "Which theme do you want to use as a base?"
drupThemeList

echo "What do you want to name the new custom theme?"
read themename

case $themechoice in

1)
installDrupTheme
;;
esac
fi

}

# Display New Wordpress Theme Menu
wordThemeMenu () {
echo "Do you want to create a new theme? [y/n]"
read newtheme

if [ $newtheme == "y" ]; then
echo "Which theme do you want to use as a base?"
wordThemeList

echo "What do you want to name the new custom theme?"
read themename

installWordTheme
fi
}

# Display list of sites available
getSiteMenu () {
for (( i=1; i<=$count; i++))
do
  echo "$i) ${arr[$i,'site']}"
done
read submenu
}

# Display and control Main Menu
getMainMenu() {
Exit=0
until [ $Exit -eq 1 ]; do
echo "------------------------------------------------"
echo "Instant Drupal/Wordpress Development Environment"
echo "---------------by hutchgrant--------------------"
echo "------------------------------------------------"
echo "1) Mount Site"
echo "2) Dismount Site"
echo "3) SSH site"
echo "4) Update All Remote"
echo "5) Update All Local"
echo "6) Add new local Drupal/Wordpress single/multi site"
echo "7) Exit"
read choice

case $choice in
1)
	getSiteMenu
	if [ ! -d "${arr[$submenu,'locMnt']}" ]; then
	echo "The directory you specified to mount the remote site to doesn't exist, Do you wish to create it? [y/n]"
	read missing
	   if [ $missing == 'y']; then
	   mkdir ${arr[$submenu,'locMnt']}
	   fi
	fi
	if ! [ -x "$(command -v sshfs)" ]; then
	  echo "Missing sshfs, attempting to install."
          sudo apt-get install sshfs -y
	fi
	sshfs -o IdentityFile=~/.ssh/id_rsa ${arr[$submenu,'ssh']}:/ ${arr[$submenu,'locMnt']}
	Exit=1
;;
2)
	getSiteMenu
	sudo umount ${arr[$submenu,'locMnt']}
	Exit=1
;;
3)
	getSiteMenu
	ssh ${arr[$submenu,'ssh']}
;;
4)  updateRemDrupal
;;
5) drush @$localDrushAlias pm-update
;;
6) getCMSMenu
;;
7) Exit=1
;;
esac
done
}

# Display and control add new CMS Menu
getCMSMenu() {
checkLAMP
echo "Which CMS do you want to use?"
echo "1) Drupal"
echo "2) Wordpress"
read cms

echo "What do you want to name the new site? (case sensitive, dont use spaces, caps or special chars)"
read newsite

echo "Do you want to create a multisite(Drupal sites must be created as regular site first)? [y/n]"
read multisite

case $cms in
     1)
	checkDrush
	if [ $multisite == "y" ]
	then
	getMultiName
	multiDrupal
	else
	singleDrupal
	fi 
	modifyApache
	drupThemeMenu
	openSite
     ;;
     2)
	checkWPCLI
	if [ $multisite == "y" ]
	then
	multiWP
	else
	singleWP
	fi 
	modifyApache
	wordThemeMenu
	openSite
     ;;
esac
}

getMainMenu
